// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apierrors "github.com/latitudesh/lsh/internal/api/errors"
	"github.com/latitudesh/lsh/internal/output"
)

// DeleteAPIKeyReader is a Reader for the DeleteAPIKey structure.
type DeleteAPIKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAPIKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := apierrors.NewUnauthorized()
		if err := result.ReadResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := apierrors.NewNotFound()
		if err := result.ReadResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /auth/api_keys/{id}] delete-api-key", response, response.Code())
	}
}

// NewDeleteAPIKeyOK creates a DeleteAPIKeyOK with default headers values
func NewDeleteAPIKeyOK() *DeleteAPIKeyOK {
	return &DeleteAPIKeyOK{}
}

/*
DeleteAPIKeyOK describes a response with status code 200, with default header values.

API Key Deleted
*/
type DeleteAPIKeyOK struct {
}

// IsSuccess returns true when this delete Api key o k response has a 2xx status code
func (o *DeleteAPIKeyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api key o k response has a 3xx status code
func (o *DeleteAPIKeyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api key o k response has a 4xx status code
func (o *DeleteAPIKeyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api key o k response has a 5xx status code
func (o *DeleteAPIKeyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api key o k response a status code equal to that given
func (o *DeleteAPIKeyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete Api key o k response
func (o *DeleteAPIKeyOK) Code() int {
	return 200
}

func (o *DeleteAPIKeyOK) Error() string {
	return fmt.Sprintf("[DELETE /auth/api_keys/{id}][%d] deleteApiKeyOK ", 200)
}

func (o *DeleteAPIKeyOK) String() string {
	return fmt.Sprintf("[DELETE /auth/api_keys/{id}][%d] deleteApiKeyOK ", 200)
}

func (o *DeleteAPIKeyOK) RenderOutput() {
	output.SuccessfulDeletion("API Key")
}

func (o *DeleteAPIKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
