// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/spf13/viper"

	apierrors "github.com/latitudesh/lsh/internal/api/errors"
	"github.com/latitudesh/lsh/internal/output"
	"github.com/latitudesh/lsh/internal/output/table"
	"github.com/latitudesh/lsh/models"
)

// UpdateAPIKeyReader is a Reader for the UpdateAPIKey structure.
type UpdateAPIKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAPIKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateAPIKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := apierrors.NewBadRequest()
		if err := result.ReadResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := apierrors.NewUnauthorized()
		if err := result.ReadResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := apierrors.NewNotFound()
		if err := result.ReadResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /auth/api_keys/{id}] update-api-key", response, response.Code())
	}
}

// NewUpdateAPIKeyOK creates a UpdateAPIKeyOK with default headers values
func NewUpdateAPIKeyOK() *UpdateAPIKeyOK {
	return &UpdateAPIKeyOK{}
}

/*
UpdateAPIKeyOK describes a response with status code 200, with default header values.

API Key Updated
*/
type UpdateAPIKeyOK struct {
	Payload *UpdateAPIKeyOKBody
}

// IsSuccess returns true when this update Api key o k response has a 2xx status code
func (o *UpdateAPIKeyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update Api key o k response has a 3xx status code
func (o *UpdateAPIKeyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update Api key o k response has a 4xx status code
func (o *UpdateAPIKeyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update Api key o k response has a 5xx status code
func (o *UpdateAPIKeyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update Api key o k response a status code equal to that given
func (o *UpdateAPIKeyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update Api key o k response
func (o *UpdateAPIKeyOK) Code() int {
	return 200
}

func (o *UpdateAPIKeyOK) Error() string {
	return fmt.Sprintf("[PUT /auth/api_keys/{id}][%d] updateApiKeyOK  %+v", 200, o.Payload)
}

func (o *UpdateAPIKeyOK) String() string {
	return fmt.Sprintf("[PUT /auth/api_keys/{id}][%d] updateApiKeyOK  %+v", 200, o.Payload)
}

func (o *UpdateAPIKeyOK) GetPayload() *UpdateAPIKeyOKBody {
	return o.Payload
}

func (o *UpdateAPIKeyOK) Render() {
	formatAsJSON := viper.GetBool("json")

	if formatAsJSON {
		o.RenderJSON()
		return
	}

	formatOutputFlag := viper.GetString("output")

	switch formatOutputFlag {
	case "json":
		o.RenderJSON()
	case "table":
		o.RenderTable()
	default:
		fmt.Println("Unsupported output format")
	}
}

func (o *UpdateAPIKeyOK) RenderJSON() {
	if !swag.IsZero(o) && !swag.IsZero(o.Payload) {
		JSONString, err := json.Marshal(o.Payload)
		if err != nil {
			fmt.Println("Could not decode the result as JSON.")
		}

		output.RenderJSON(JSONString)
	}
}

type UpdateAPIKeyTableRow struct {
	ID string `json:"id,omitempty"`
	TokenLastSlice string `json:"token_last_slice,omitempty"`
	User string `json:"user,omitempty"`
	APIVersion string `json:"api_version,omitempty"`
	LastUsedAt string `json:"last_used_at,omitempty"`
	Name string `json:"name,omitempty"`
}

func (o *UpdateAPIKeyOK) RenderTable() {
	attributes := o.Payload.Data.Attributes

	var rows []UpdateAPIKeyTableRow

	row := UpdateAPIKeyTableRow{
		ID:        	 					 table.String(o.Payload.Data.ID),
		TokenLastSlice:        table.String(attributes.TokenLastSlice),
		User:    							 table.String(attributes.User.Email),
		APIVersion:     			 table.String(attributes.APIVersion),
		LastUsedAt: 					 table.DateTime(attributes.LastUsedAt),
		Name: 				 				 table.String(attributes.Name),
	}

	rows = append(rows, row)

	var interfaceRows []interface{}

	for _, row := range rows {
		interfaceRows = append(interfaceRows, row)
	}

	table.Render(interfaceRows)
}

func (o *UpdateAPIKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(UpdateAPIKeyOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
UpdateAPIKeyOKBody update API key o k body
swagger:model UpdateAPIKeyOKBody
*/
type UpdateAPIKeyOKBody struct {

	// data
	Data *models.APIKey `json:"data,omitempty"`
}

// Validate validates this update API key o k body
func (o *UpdateAPIKeyOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateAPIKeyOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updateApiKeyOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updateApiKeyOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this update API key o k body based on the context it is used
func (o *UpdateAPIKeyOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateAPIKeyOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updateApiKeyOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updateApiKeyOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateAPIKeyOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateAPIKeyOKBody) UnmarshalBinary(b []byte) error {
	var res UpdateAPIKeyOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
