// Code generated by go-swagger; DO NOT EDIT.

package deploy_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetServerDeployConfigParams creates a new GetServerDeployConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetServerDeployConfigParams() *GetServerDeployConfigParams {
	return &GetServerDeployConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetServerDeployConfigParamsWithTimeout creates a new GetServerDeployConfigParams object
// with the ability to set a timeout on a request.
func NewGetServerDeployConfigParamsWithTimeout(timeout time.Duration) *GetServerDeployConfigParams {
	return &GetServerDeployConfigParams{
		timeout: timeout,
	}
}

// NewGetServerDeployConfigParamsWithContext creates a new GetServerDeployConfigParams object
// with the ability to set a context for a request.
func NewGetServerDeployConfigParamsWithContext(ctx context.Context) *GetServerDeployConfigParams {
	return &GetServerDeployConfigParams{
		Context: ctx,
	}
}

// NewGetServerDeployConfigParamsWithHTTPClient creates a new GetServerDeployConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetServerDeployConfigParamsWithHTTPClient(client *http.Client) *GetServerDeployConfigParams {
	return &GetServerDeployConfigParams{
		HTTPClient: client,
	}
}

/*
GetServerDeployConfigParams contains all the parameters to send to the API endpoint

	for the get server deploy config operation.

	Typically these are written to a http.Request.
*/
type GetServerDeployConfigParams struct {

	// APIVersion.
	//
	// Default: "2023-06-01"
	APIVersion *string

	/* ServerID.

	   The Server ID
	*/
	ServerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get server deploy config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetServerDeployConfigParams) WithDefaults() *GetServerDeployConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get server deploy config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetServerDeployConfigParams) SetDefaults() {
	var (
		aPIVersionDefault = string("2023-06-01")
	)

	val := GetServerDeployConfigParams{
		APIVersion: &aPIVersionDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get server deploy config params
func (o *GetServerDeployConfigParams) WithTimeout(timeout time.Duration) *GetServerDeployConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get server deploy config params
func (o *GetServerDeployConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get server deploy config params
func (o *GetServerDeployConfigParams) WithContext(ctx context.Context) *GetServerDeployConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get server deploy config params
func (o *GetServerDeployConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get server deploy config params
func (o *GetServerDeployConfigParams) WithHTTPClient(client *http.Client) *GetServerDeployConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get server deploy config params
func (o *GetServerDeployConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the get server deploy config params
func (o *GetServerDeployConfigParams) WithAPIVersion(aPIVersion *string) *GetServerDeployConfigParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get server deploy config params
func (o *GetServerDeployConfigParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithServerID adds the serverID to the get server deploy config params
func (o *GetServerDeployConfigParams) WithServerID(serverID string) *GetServerDeployConfigParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the get server deploy config params
func (o *GetServerDeployConfigParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WriteToRequest writes these params to a swagger request
func (o *GetServerDeployConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIVersion != nil {

		// header param API-Version
		if err := r.SetHeaderParam("API-Version", *o.APIVersion); err != nil {
			return err
		}
	}

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
