// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/latitudesh/cli/client/teams"
	"github.com/latitudesh/cli/internal/utils"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationTeamsGetTeamCmd returns a cmd to handle operation getTeam
func makeOperationTeamsGetTeamCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "get-team",
		Short: ``,
		RunE:  runOperationTeamsGetTeam,
	}

	if err := registerOperationTeamsGetTeamParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationTeamsGetTeam uses cmd flags to call endpoint api
func runOperationTeamsGetTeam(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := teams.NewGetTeamParams()
	if err, _ := retrieveOperationTeamsGetTeamAPIVersionFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationTeamsGetTeamResult(appCli.Teams.GetTeam(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(utils.PrettifyJson(msgStr))
	}
	return nil
}

// registerOperationTeamsGetTeamParamFlags registers all flags needed to fill params
func registerOperationTeamsGetTeamParamFlags(cmd *cobra.Command) error {
	if err := registerOperationTeamsGetTeamAPIVersionParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationTeamsGetTeamAPIVersionParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	apiVersionDescription := ``

	var apiVersionFlagName string
	if cmdPrefix == "" {
		apiVersionFlagName = "API-Version"
	} else {
		apiVersionFlagName = fmt.Sprintf("%v.API-Version", cmdPrefix)
	}

	var apiVersionFlagDefault string = "2023-06-01"

	_ = cmd.PersistentFlags().String(apiVersionFlagName, apiVersionFlagDefault, apiVersionDescription)

	return nil
}

func retrieveOperationTeamsGetTeamAPIVersionFlag(m *teams.GetTeamParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("API-Version") {

		var apiVersionFlagName string
		if cmdPrefix == "" {
			apiVersionFlagName = "API-Version"
		} else {
			apiVersionFlagName = fmt.Sprintf("%v.API-Version", cmdPrefix)
		}

		apiVersionFlagValue, err := cmd.Flags().GetString(apiVersionFlagName)
		if err != nil {
			return err, false
		}
		m.APIVersion = &apiVersionFlagValue

	}
	return nil, retAdded
}

// parseOperationTeamsGetTeamResult parses request result and return the string content
func parseOperationTeamsGetTeamResult(resp0 *teams.GetTeamOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*teams.GetTeamOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
