// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/latitudesh/lsh/client/servers"
	"github.com/latitudesh/lsh/internal"
	"github.com/latitudesh/lsh/internal/utils"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationServersServerUnscheduleDeletionCmd returns a cmd to handle operation serverUnscheduleDeletion
func makeOperationServersServerUnscheduleDeletionCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "unschedule-deletion",
		Short: `Unschedules the server removal at the end of the billing cycle.`,
		RunE:  runOperationServersServerUnscheduleDeletion,
	}

	if err := registerOperationServersServerUnscheduleDeletionParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationServersServerUnscheduleDeletion uses cmd flags to call endpoint api
func runOperationServersServerUnscheduleDeletion(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := servers.NewServerUnscheduleDeletionParams()
	if err, _ := retrieveOperationServersServerUnscheduleDeletionServerIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationServersServerUnscheduleDeletionResult(appCli.Servers.ServerUnscheduleDeletion(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		utils.PrintOutput(msgStr)
	}
	return nil
}

// registerOperationServersServerUnscheduleDeletionParamFlags registers all flags needed to fill params
func registerOperationServersServerUnscheduleDeletionParamFlags(cmd *cobra.Command) error {
	if err := registerOperationServersServerUnscheduleDeletionServerIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationServersServerUnscheduleDeletionServerIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	serverIdDescription := `The Server Id (Required).`

	var serverIdFlagName string
	if cmdPrefix == "" {
		serverIdFlagName = "id"
	} else {
		serverIdFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var serverIdFlagDefault string

	_ = cmd.PersistentFlags().String(serverIdFlagName, serverIdFlagDefault, serverIdDescription)
	cmd.MarkPersistentFlagRequired(serverIdFlagName)

	return nil
}

func retrieveOperationServersServerUnscheduleDeletionServerIDFlag(m *servers.ServerUnscheduleDeletionParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var serverIdFlagName string
		if cmdPrefix == "" {
			serverIdFlagName = "id"
		} else {
			serverIdFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		serverIdFlagValue, err := cmd.Flags().GetString(serverIdFlagName)
		if err != nil {
			return err, false
		}
		m.ServerID = serverIdFlagValue

	}
	return nil, retAdded
}

// parseOperationServersServerUnscheduleDeletionResult parses request result and return the string content
func parseOperationServersServerUnscheduleDeletionResult(resp0 *servers.ServerUnscheduleDeletionNoContent, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning serverUnscheduleDeletionNoContent is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*servers.ServerUnscheduleDeletionForbidden)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		notFoundErrorMessage, err := internal.ParseNotFoundError(respErr)

		if err != nil {
			return "", err
		}

		if len(notFoundErrorMessage) > 0 {
			return notFoundErrorMessage, nil
		}

		return "", respErr
	}

	// warning: non schema response serverUnscheduleDeletionNoContent is not supported by go-swagger cli yet.

	return "", nil
}
