// Code generated by go-swagger; DO NOT EDIT.

package power_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateServerActionParams creates a new CreateServerActionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateServerActionParams() *CreateServerActionParams {
	return &CreateServerActionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateServerActionParamsWithTimeout creates a new CreateServerActionParams object
// with the ability to set a timeout on a request.
func NewCreateServerActionParamsWithTimeout(timeout time.Duration) *CreateServerActionParams {
	return &CreateServerActionParams{
		timeout: timeout,
	}
}

// NewCreateServerActionParamsWithContext creates a new CreateServerActionParams object
// with the ability to set a context for a request.
func NewCreateServerActionParamsWithContext(ctx context.Context) *CreateServerActionParams {
	return &CreateServerActionParams{
		Context: ctx,
	}
}

// NewCreateServerActionParamsWithHTTPClient creates a new CreateServerActionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateServerActionParamsWithHTTPClient(client *http.Client) *CreateServerActionParams {
	return &CreateServerActionParams{
		HTTPClient: client,
	}
}

/*
CreateServerActionParams contains all the parameters to send to the API endpoint

	for the create server action operation.

	Typically these are written to a http.Request.
*/
type CreateServerActionParams struct {

	// APIVersion.
	//
	// Default: "2023-06-01"
	APIVersion *string

	// Body.
	Body CreateServerActionBody

	// ServerID.
	ServerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create server action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateServerActionParams) WithDefaults() *CreateServerActionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create server action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateServerActionParams) SetDefaults() {
	var (
		aPIVersionDefault = string("2023-06-01")
	)

	val := CreateServerActionParams{
		APIVersion: &aPIVersionDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the create server action params
func (o *CreateServerActionParams) WithTimeout(timeout time.Duration) *CreateServerActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create server action params
func (o *CreateServerActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create server action params
func (o *CreateServerActionParams) WithContext(ctx context.Context) *CreateServerActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create server action params
func (o *CreateServerActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create server action params
func (o *CreateServerActionParams) WithHTTPClient(client *http.Client) *CreateServerActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create server action params
func (o *CreateServerActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the create server action params
func (o *CreateServerActionParams) WithAPIVersion(aPIVersion *string) *CreateServerActionParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the create server action params
func (o *CreateServerActionParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithBody adds the body to the create server action params
func (o *CreateServerActionParams) WithBody(body CreateServerActionBody) *CreateServerActionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create server action params
func (o *CreateServerActionParams) SetBody(body CreateServerActionBody) {
	o.Body = body
}

// WithServerID adds the serverID to the create server action params
func (o *CreateServerActionParams) WithServerID(serverID string) *CreateServerActionParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the create server action params
func (o *CreateServerActionParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateServerActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIVersion != nil {

		// header param API-Version
		if err := r.SetHeaderParam("API-Version", *o.APIVersion); err != nil {
			return err
		}
	}
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
