// Code generated by go-swagger; DO NOT EDIT.

package power_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new power actions API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for power actions API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateServerAction(params *CreateServerActionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateServerActionCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
	CreateServerAction runs server action

	Performs an action on a given server:

- `power_on`
- `power_off`
- `reboot`
*/
func (a *Client) CreateServerAction(params *CreateServerActionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateServerActionCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateServerActionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "create-server-action",
		Method:             "POST",
		PathPattern:        "/servers/{server_id}/actions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateServerActionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateServerActionCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for create-server-action: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
