// Code generated by go-swagger; DO NOT EDIT.

package virtual_network_assignments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteVirtualNetworksAssignmentsParams creates a new DeleteVirtualNetworksAssignmentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteVirtualNetworksAssignmentsParams() *DeleteVirtualNetworksAssignmentsParams {
	return &DeleteVirtualNetworksAssignmentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVirtualNetworksAssignmentsParamsWithTimeout creates a new DeleteVirtualNetworksAssignmentsParams object
// with the ability to set a timeout on a request.
func NewDeleteVirtualNetworksAssignmentsParamsWithTimeout(timeout time.Duration) *DeleteVirtualNetworksAssignmentsParams {
	return &DeleteVirtualNetworksAssignmentsParams{
		timeout: timeout,
	}
}

// NewDeleteVirtualNetworksAssignmentsParamsWithContext creates a new DeleteVirtualNetworksAssignmentsParams object
// with the ability to set a context for a request.
func NewDeleteVirtualNetworksAssignmentsParamsWithContext(ctx context.Context) *DeleteVirtualNetworksAssignmentsParams {
	return &DeleteVirtualNetworksAssignmentsParams{
		Context: ctx,
	}
}

// NewDeleteVirtualNetworksAssignmentsParamsWithHTTPClient creates a new DeleteVirtualNetworksAssignmentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteVirtualNetworksAssignmentsParamsWithHTTPClient(client *http.Client) *DeleteVirtualNetworksAssignmentsParams {
	return &DeleteVirtualNetworksAssignmentsParams{
		HTTPClient: client,
	}
}

/*
DeleteVirtualNetworksAssignmentsParams contains all the parameters to send to the API endpoint

	for the delete virtual networks assignments operation.

	Typically these are written to a http.Request.
*/
type DeleteVirtualNetworksAssignmentsParams struct {

	// AssignmentID.
	AssignmentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete virtual networks assignments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteVirtualNetworksAssignmentsParams) WithDefaults() *DeleteVirtualNetworksAssignmentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete virtual networks assignments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteVirtualNetworksAssignmentsParams) SetDefaults() {
	val := DeleteVirtualNetworksAssignmentsParams{}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the delete virtual networks assignments params
func (o *DeleteVirtualNetworksAssignmentsParams) WithTimeout(timeout time.Duration) *DeleteVirtualNetworksAssignmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete virtual networks assignments params
func (o *DeleteVirtualNetworksAssignmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete virtual networks assignments params
func (o *DeleteVirtualNetworksAssignmentsParams) WithContext(ctx context.Context) *DeleteVirtualNetworksAssignmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete virtual networks assignments params
func (o *DeleteVirtualNetworksAssignmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete virtual networks assignments params
func (o *DeleteVirtualNetworksAssignmentsParams) WithHTTPClient(client *http.Client) *DeleteVirtualNetworksAssignmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete virtual networks assignments params
func (o *DeleteVirtualNetworksAssignmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssignmentID adds the assignmentID to the delete virtual networks assignments params
func (o *DeleteVirtualNetworksAssignmentsParams) WithAssignmentID(assignmentID string) *DeleteVirtualNetworksAssignmentsParams {
	o.SetAssignmentID(assignmentID)
	return o
}

// SetAssignmentID adds the assignmentId to the delete virtual networks assignments params
func (o *DeleteVirtualNetworksAssignmentsParams) SetAssignmentID(assignmentID string) {
	o.AssignmentID = assignmentID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVirtualNetworksAssignmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param assignment_id
	if err := r.SetPathParam("assignment_id", o.AssignmentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
