// Code generated by go-swagger; DO NOT EDIT.

package ip_addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetIPParams creates a new GetIPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetIPParams() *GetIPParams {
	return &GetIPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetIPParamsWithTimeout creates a new GetIPParams object
// with the ability to set a timeout on a request.
func NewGetIPParamsWithTimeout(timeout time.Duration) *GetIPParams {
	return &GetIPParams{
		timeout: timeout,
	}
}

// NewGetIPParamsWithContext creates a new GetIPParams object
// with the ability to set a context for a request.
func NewGetIPParamsWithContext(ctx context.Context) *GetIPParams {
	return &GetIPParams{
		Context: ctx,
	}
}

// NewGetIPParamsWithHTTPClient creates a new GetIPParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetIPParamsWithHTTPClient(client *http.Client) *GetIPParams {
	return &GetIPParams{
		HTTPClient: client,
	}
}

/*
GetIPParams contains all the parameters to send to the API endpoint

	for the get ip operation.

	Typically these are written to a http.Request.
*/
type GetIPParams struct {

	// Default: "2023-06-01"
	APIVersion *string

	/* ExtraFieldsIPAddresses.

	   The `region` and `server` are provided as extra attributes that is lazy loaded. To request it, just set `extra_fields[ip_addresses]=region,server` in the query string.
	*/
	ExtraFieldsIPAddresses *string

	/* ID.

	   The IP Address ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get ip params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIPParams) WithDefaults() *GetIPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get ip params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get ip params
func (o *GetIPParams) WithTimeout(timeout time.Duration) *GetIPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ip params
func (o *GetIPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ip params
func (o *GetIPParams) WithContext(ctx context.Context) *GetIPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ip params
func (o *GetIPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ip params
func (o *GetIPParams) WithHTTPClient(client *http.Client) *GetIPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ip params
func (o *GetIPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExtraFieldsIPAddresses adds the extraFieldsIPAddresses to the get ip params
func (o *GetIPParams) WithExtraFieldsIPAddresses(extraFieldsIPAddresses *string) *GetIPParams {
	o.SetExtraFieldsIPAddresses(extraFieldsIPAddresses)
	return o
}

// SetExtraFieldsIPAddresses adds the extraFieldsIpAddresses to the get ip params
func (o *GetIPParams) SetExtraFieldsIPAddresses(extraFieldsIPAddresses *string) {
	o.ExtraFieldsIPAddresses = extraFieldsIPAddresses
}

// WithID adds the id to the get ip params
func (o *GetIPParams) WithID(id string) *GetIPParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get ip params
func (o *GetIPParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetIPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ExtraFieldsIPAddresses != nil {

		// query param extra_fields[ip_addresses]
		var qrExtraFieldsIPAddresses string

		if o.ExtraFieldsIPAddresses != nil {
			qrExtraFieldsIPAddresses = *o.ExtraFieldsIPAddresses
		}
		qExtraFieldsIPAddresses := qrExtraFieldsIPAddresses
		if qExtraFieldsIPAddresses != "" {

			if err := r.SetQueryParam("extra_fields[ip_addresses]", qExtraFieldsIPAddresses); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
