// Code generated by go-swagger; DO NOT EDIT.

package v_p_n_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteVpnSessionParams creates a new DeleteVpnSessionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteVpnSessionParams() *DeleteVpnSessionParams {
	return &DeleteVpnSessionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVpnSessionParamsWithTimeout creates a new DeleteVpnSessionParams object
// with the ability to set a timeout on a request.
func NewDeleteVpnSessionParamsWithTimeout(timeout time.Duration) *DeleteVpnSessionParams {
	return &DeleteVpnSessionParams{
		timeout: timeout,
	}
}

// NewDeleteVpnSessionParamsWithContext creates a new DeleteVpnSessionParams object
// with the ability to set a context for a request.
func NewDeleteVpnSessionParamsWithContext(ctx context.Context) *DeleteVpnSessionParams {
	return &DeleteVpnSessionParams{
		Context: ctx,
	}
}

// NewDeleteVpnSessionParamsWithHTTPClient creates a new DeleteVpnSessionParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteVpnSessionParamsWithHTTPClient(client *http.Client) *DeleteVpnSessionParams {
	return &DeleteVpnSessionParams{
		HTTPClient: client,
	}
}

/*
DeleteVpnSessionParams contains all the parameters to send to the API endpoint

	for the delete vpn session operation.

	Typically these are written to a http.Request.
*/
type DeleteVpnSessionParams struct {

	// APIVersion.
	//
	// Default: "2023-06-01"
	APIVersion *string

	// VpnSessionID.
	VpnSessionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete vpn session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteVpnSessionParams) WithDefaults() *DeleteVpnSessionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete vpn session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteVpnSessionParams) SetDefaults() {
	var (
		aPIVersionDefault = string("2023-06-01")
	)

	val := DeleteVpnSessionParams{
		APIVersion: &aPIVersionDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the delete vpn session params
func (o *DeleteVpnSessionParams) WithTimeout(timeout time.Duration) *DeleteVpnSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete vpn session params
func (o *DeleteVpnSessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete vpn session params
func (o *DeleteVpnSessionParams) WithContext(ctx context.Context) *DeleteVpnSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete vpn session params
func (o *DeleteVpnSessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete vpn session params
func (o *DeleteVpnSessionParams) WithHTTPClient(client *http.Client) *DeleteVpnSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete vpn session params
func (o *DeleteVpnSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the delete vpn session params
func (o *DeleteVpnSessionParams) WithAPIVersion(aPIVersion *string) *DeleteVpnSessionParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the delete vpn session params
func (o *DeleteVpnSessionParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithVpnSessionID adds the vpnSessionID to the delete vpn session params
func (o *DeleteVpnSessionParams) WithVpnSessionID(vpnSessionID string) *DeleteVpnSessionParams {
	o.SetVpnSessionID(vpnSessionID)
	return o
}

// SetVpnSessionID adds the vpnSessionId to the delete vpn session params
func (o *DeleteVpnSessionParams) SetVpnSessionID(vpnSessionID string) {
	o.VpnSessionID = vpnSessionID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVpnSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIVersion != nil {

		// header param API-Version
		if err := r.SetHeaderParam("API-Version", *o.APIVersion); err != nil {
			return err
		}
	}

	// path param vpn_session_id
	if err := r.SetPathParam("vpn_session_id", o.VpnSessionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
