// Code generated by go-swagger; DO NOT EDIT.

package v_p_n_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetVpnSessionsParams creates a new GetVpnSessionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetVpnSessionsParams() *GetVpnSessionsParams {
	return &GetVpnSessionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetVpnSessionsParamsWithTimeout creates a new GetVpnSessionsParams object
// with the ability to set a timeout on a request.
func NewGetVpnSessionsParamsWithTimeout(timeout time.Duration) *GetVpnSessionsParams {
	return &GetVpnSessionsParams{
		timeout: timeout,
	}
}

// NewGetVpnSessionsParamsWithContext creates a new GetVpnSessionsParams object
// with the ability to set a context for a request.
func NewGetVpnSessionsParamsWithContext(ctx context.Context) *GetVpnSessionsParams {
	return &GetVpnSessionsParams{
		Context: ctx,
	}
}

// NewGetVpnSessionsParamsWithHTTPClient creates a new GetVpnSessionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetVpnSessionsParamsWithHTTPClient(client *http.Client) *GetVpnSessionsParams {
	return &GetVpnSessionsParams{
		HTTPClient: client,
	}
}

/*
GetVpnSessionsParams contains all the parameters to send to the API endpoint

	for the get vpn sessions operation.

	Typically these are written to a http.Request.
*/
type GetVpnSessionsParams struct {

	// APIVersion.
	//
	// Default: "2023-06-01"
	APIVersion *string

	// FilterLocation.
	FilterLocation *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get vpn sessions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetVpnSessionsParams) WithDefaults() *GetVpnSessionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get vpn sessions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetVpnSessionsParams) SetDefaults() {
	var (
		aPIVersionDefault = string("2023-06-01")
	)

	val := GetVpnSessionsParams{
		APIVersion: &aPIVersionDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get vpn sessions params
func (o *GetVpnSessionsParams) WithTimeout(timeout time.Duration) *GetVpnSessionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get vpn sessions params
func (o *GetVpnSessionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get vpn sessions params
func (o *GetVpnSessionsParams) WithContext(ctx context.Context) *GetVpnSessionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get vpn sessions params
func (o *GetVpnSessionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get vpn sessions params
func (o *GetVpnSessionsParams) WithHTTPClient(client *http.Client) *GetVpnSessionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get vpn sessions params
func (o *GetVpnSessionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the get vpn sessions params
func (o *GetVpnSessionsParams) WithAPIVersion(aPIVersion *string) *GetVpnSessionsParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get vpn sessions params
func (o *GetVpnSessionsParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithFilterLocation adds the filterLocation to the get vpn sessions params
func (o *GetVpnSessionsParams) WithFilterLocation(filterLocation *string) *GetVpnSessionsParams {
	o.SetFilterLocation(filterLocation)
	return o
}

// SetFilterLocation adds the filterLocation to the get vpn sessions params
func (o *GetVpnSessionsParams) SetFilterLocation(filterLocation *string) {
	o.FilterLocation = filterLocation
}

// WriteToRequest writes these params to a swagger request
func (o *GetVpnSessionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIVersion != nil {

		// header param API-Version
		if err := r.SetHeaderParam("API-Version", *o.APIVersion); err != nil {
			return err
		}
	}

	if o.FilterLocation != nil {

		// query param filter[location]
		var qrFilterLocation string

		if o.FilterLocation != nil {
			qrFilterLocation = *o.FilterLocation
		}
		qFilterLocation := qrFilterLocation
		if qFilterLocation != "" {

			if err := r.SetQueryParam("filter[location]", qFilterLocation); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
